job1:
  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian:9
  script:
    #- mkdir -p build-bcg729
    #- cd build-bcg729
    #- cmake .. -DENABLE_TESTS=YES
    #- make
    #- make install
    - cd /usr/
    - ls -la
    - cd share
    - ls -la