image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian:9
before_script: 
    - sudo apt-get install wget unzip
stages:
  - build
  - test
build:
  stage: build
  tags: [ "docker" ]
  script:
    - mkdir -p build-bcg729
    - cd build-bcg729
    - cmake .. -DENABLE_TESTS=YES
    - make
  artifacts:
    #untracked: true
    paths:
      - build-bcg729/test/*
    
test:
  stage: test
  tags: [ "docker" ]
  script:
    - cd build-bcg729/test
    - ./testCampaignAll
  dependencies:
    - build